name: First Workflow
on: push
jobs:
  run-lint:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ESLint
      run: npm install -D eslint
    - name: Run ESLint
      run: npx eslint --ext .jsx --fix src
    - name: Install Vite
      run: npm install -D vite
    - name: Run tests
      run: npx vitest run
    - name: Build
      run: npx vite build