name: First Workflow
on: push
jobs:
  run-lint:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Install ESLint
      run: npm install -D eslint
    - name: Run ESLint
      run: npx eslint --ext .jsx --fix src