name: First Workflow
on: push
jobs:
  download-artifact:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
  run-lint:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R