name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - name: Print goodbye
      run: echo "Done - bye!"